"""empty message

Revision ID: 4fa43b806b08
Revises: c460e8376896
Create Date: 2025-06-08 16:17:18.350596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa43b806b08'
down_revision = 'c460e8376896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pagos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
