"""empty message

Revision ID: 5ae295ffd605
Revises: 
Create Date: 2025-06-15 07:31:51.919162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae295ffd605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hogar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hogar_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('favorito_recetas', sa.JSON(), nullable=True),
    sa.Column('deseado_recetas', sa.JSON(), nullable=True),
    sa.Column('favorito_peliculas', sa.JSON(), nullable=True),
    sa.Column('hogar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('comida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('recetas', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_hogar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finanzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('done_by', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.Column('tarea', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['done_by'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.Column('finanzas_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finanzas_id'], ['finanzas.id'], ),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.Column('pagos_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['pagos_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pagos')
    op.drop_table('pagos')
    op.drop_table('tareas')
    op.drop_table('finanzas')
    op.drop_table('favoritos_hogar')
    op.drop_table('comida')
    op.drop_table('user')
    op.drop_table('hogar')
    # ### end Alembic commands ###
