"""empty message

Revision ID: 8e199992d8be
Revises: 0763d677d453
Create Date: 2025-05-28 08:48:03.523030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e199992d8be'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hogar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hogar_name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hogar_name')
    )
    op.create_table('comida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('recetas', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_hogar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finanzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.Column('tarea', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['done_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.Column('finanzas_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finanzas_id'], ['finanzas.id'], ),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hogar_id', sa.Integer(), nullable=False),
    sa.Column('pagos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogar.id'], ),
    sa.ForeignKeyConstraint(['pagos_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('favorito_recetas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('favorito_peliculas', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('favorito_peliculas')
        batch_op.drop_column('favorito_recetas')
        batch_op.drop_column('user_name')

    op.drop_table('user_pagos')
    op.drop_table('pagos')
    op.drop_table('tareas')
    op.drop_table('finanzas')
    op.drop_table('favoritos_hogar')
    op.drop_table('comida')
    op.drop_table('hogar')
    # ### end Alembic commands ###
