"""empty message

Revision ID: ba6261d7059c
Revises: 0245fba37812
Create Date: 2025-06-11 09:10:28.589194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6261d7059c'
down_revision = '0245fba37812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('compartido_con', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('frecuencia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_limite', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=True))
        batch_op.alter_column('finanzas_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('finanzas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('fecha')
        batch_op.drop_column('tipo')
        batch_op.drop_column('fecha_limite')
        batch_op.drop_column('frecuencia')
        batch_op.drop_column('categoria')
        batch_op.drop_column('compartido_con')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
