"""empty message

Revision ID: c460e8376896
Revises: d22823fb986a
Create Date: 2025-06-07 16:53:38.528317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c460e8376896'
down_revision = 'd22823fb986a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hogar', schema=None) as batch_op:
        batch_op.drop_constraint('hogar_hogar_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hogar', schema=None) as batch_op:
        batch_op.create_unique_constraint('hogar_hogar_name_key', ['hogar_name'])

    # ### end Alembic commands ###
